### ISSUE TITLE
Installing via composer installs zend components, not laminas

### ISSUE THREAD

**Issue by bogal** [neilime/zf-twbs-helper-module#33]
As the title suggests, when installed via composer with the command:
`composer require neilime/zf-twbs-helper-module`
...it installs a lot of zend components, not laminas components.

Composer output from above command:

> Using version ^2.1 for neilime/zf-twbs-helper-module
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing zendframework/zend-progressbar (2.7.0): Downloading (100%)
  - Installing zendframework/zend-paginator (2.8.2): Downloading (100%)

  Please select which config file you wish to inject 'Zend\Paginator' into:
  [0] Do not inject
  [1] config/modules.config.php
  [2] config/development.config.php.dist
  Make your selection (default is 1):

**Comment by rarog** [comment]
You have 2 choices for now, as the migration to Laminas wasn't released yet officially.
1) Use the current release and additionally install the following 2 packages:
    https://github.com/laminas/laminas-zendframework-bridge
    https://github.com/laminas/laminas-dependency-plugin
2) Configure this package as VCS repository (https://getcomposer.org/doc/05-repositories.md) and let it use dev-master or freeze it to this commit: https://github.com/neilime/zf-twbs-helper-module/commit/d1502e6020a5df8779d40fd209dc0aa8d0d03b9b

**Comment by neilime** [comment]
I will release the "Laminas" version very soon (I need to fix some CI issues before)

**Comment by bogal** [comment]
Thanks, i think i can wait for the official Laminas version.
