### ISSUE TITLE
The form helpers are rendering an extra '%s'

### ISSUE THREAD

**Issue by Saeven** [neilime/zf-twbs-helper-module#9]
**Describe the bug**

Printing an element in the traditional manner, with:

    {{ formElement(profileForm.get('email') }}

Results in the printing of an extra %s character.

```
<div class="form-group">
    <input type="email" name="email" maxlength="254" required="required" autofocus="autofocus" placeholder="Email" class="forms_field-input form-control" value="">%s
</div>
```

**To Reproduce**

1. Load TwbsHelper in application.config.php
2. Create a simple form with this init method

```
    public function init()
    {
        $this->add([
            'name' => 'email',
            'id' => 'email',
            'type' => Email::class,
            'options' => [
                'label' => _("Your Email Address"),
                'label_attributes' => ['for' => 'email'],
            ],
            'attributes' => [
                'maxlength' => 254,
            ],
        ]);
    }
```

3. Load the form object into a template, and print the form.

**Expected behavior**
The form is printed as expected.

**Screenshots**
https://imgur.com/a/X69TVNX

**Desktop (please complete the following information):**
 - OS: OSX Mojave
 - Browser Any
 - Version Any

**Additional context**

The error is caused by this block in TwbsHelper\Form\View\Helper\FormElement

        // Add a sprintf directive for correct render of errors
        if (!in_array($sElementType, $this->options->getIgnoredViewHelpers()) &&
            !($oElement instanceof Collection)
        ) {
            $sMarkup .= "%s";
        }

**Comment by neilime** [comment]
Fixed, thanks your PR
